eshop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

eshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
]

eshop/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                    on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    # DecimalField是Python的decimal.Decimal，用于处理固定精度。
    # 金钱处理应当都使用DecimalField
    price = models.DecimalField(max_digits=10, decimal_places=2)
    availabel = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

eshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from .recommender import Recommender
from cart.form import CartAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(availabel=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    return render(request, 'shop/product/list.html', # 模板路径开头不能有斜杠
            {'category': category,
             'categories': categories,
             'products': products,
            })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, availabel=True)
    cart_product_form = CartAddProductForm()
    
    # 获取推荐商品
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    print('>>>>>><<<<<<<', recommended_products)
    
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form,
            'recommended_products': recommended_products
        }
    )

eshop/shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}EShop{% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style type="text/css">
        /*h1, h2, h3, h4, h5, h6, body, html {*/
        /*    margin: 0px;*/
            
        /*}*/
        .brand-logo {
            padding-left: 20px !important;
        }
        
        .inline-img {
            max-width: 52px;
            max-height: 52px;
        }
        .img-td {
            padding-top: 0px;
            padding-bottom: 0px;
        }
        .page-footer {
            padding-top: 0 !important;
        }
        
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }
        
        main {
            flex: 1 0 auto;
        }
        
        /* back to top css */
        .back-to-top {
            position: fixed;
            right: 1%;
            bottom: -7.5%;
            height: 15px;
            width: 40px;
            padding: 3px 5px;
            font-size: 10px;
            font-weight: bold;
            color: transparent;
            opacity: 0.5;
            z-index: 3;
            visibility: hidden;
            text-align: center;
            text-decoration: none;
            text-transform: uppercase;
            transition: all 0.25s ease-in-out;
            background-color: #1cf302;
        }
        
        .back-to-top:hover,
        .back-to-top:focus {
            opacity: 1;
            text-decoration: none;
        }
        
        .back-to-top:focus {
            outline: thin dotted;
        }
        
        .back-to-top::before,
        .back-to-top::after {
            content: '';
            position: absolute;
            left: 0;
            width: 0;
            height: 0;
            border: 20px solid transparent;
            border-top: 0;
        }
        
        .back-to-top::before {
            top: -20px;
            z-index: 4;
            border-bottom: 20px solid #858585;
        }
        
        .back-to-top::after {
            bottom: 0;
            z-index: 5;
            border-bottom: 20px solid #505050;
        }
        
        .back-to-top:hover,
        .back-to-top:focus {
            height: 40px;
            color: #212223;
        }
        
        .show-back-to-top {
            display: block;
            bottom: 1.25%;
            visibility: visible;
        }
        
        /* Basic styles below this line. */
        
        html {
            box-sizing: border-box;
        }
        
        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }
        
    </style>
</head>
<body>
    <header class="scrollspy" id="header">
        <nav>
            <div class="nav-wrapper blue hoverable">
                
                <a href="/" class="brand-logo">EShop</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="#"><i class="material-icons">shopping_cart</i></a></li>
                <li>
                    <a href="{% url 'cart:cart_detail' %}">
                        {% with total_items=cart|length %}
                            {% if cart|length > 0 %}
                                <span class="new badge">{{ total_items }}</span>
                            {% else %}
                                <span class="new badge">0</span>
                            {% endif %}
                        {% endwith %}
                    </a>
                </li>
                </ul>
            </div>
        </nav>
    </header>
    
    
    <main>
        {% block content %}
        {% endblock %}
        
        <div class="fixed-action-btn" id="scroll-top">
            <a href="#header" class="back-to-top">Top</a>
        </div>
        
    </main>
    
    
    
    <footer class="page-footer blue">
        <div class="container">
            <div class="row">
                <div class="col l6 m5 s12">
                    <h5 class="white-text">页尾</h5>
                    <p class="grey-text text-lighten-4">页尾内容...</p>
                </div>
                <div class="col l4 m5 offset-12 s12">
                    <h5 class="white-text">链接</h5>
                    <ul>
                        <li><a href="#" class="grey-text text-lighten-3">链接 1</a></li>
                        <li><a href="#" class="grey-text text-lighten-3">链接 2</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                &copy; 2018 版权所有
                <a class="grey-text text-lighten-4 right" href="#">更多连接</a>
            </div>
        </div>
    </footer>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
        // scroll top
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelector('#scroll-top');
            var instance = M.FloatingActionButton.init(elems, {
                direction: 'left',
            });
        });
        
        // init parallax
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.parallax');
            var instance = M.Parallax.init(elems);
        });
        
        // init materialbox
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.materialboxed');
            var instance = M.Materialbox.init(elems);
        });
        
        $(document).ready(function() {
            // Check distance to top and display back-to-top.
            $(window).scroll(function() {
                if ($(this).scrollTop() > 600) {
                    $('.back-to-top').addClass('show-back-to-top');
                }
                else {
                    $('.back-to-top').removeClass('show-back-to-top');
                }
            });
            
            // Click event to scroll to top.
            $('.back-to-top').click(function() {
                $('html, body').animate({ scrollTop: 0 }, 800);
                return false;
            });
        });
    </script>
</body>
</html>