eshop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

eshop/coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

eshop/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf,
        name='admin_order_pdf'
    ),
]

eshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
]

eshop/cart/models.py
from django.db import models

# Create your models here.

eshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from shop.recommender import Recommender
from .cart import Cart
from .form import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST #只允许POST方法
def cart_add(request, product_id):
    '''
    添加商品到购物车
    '''
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )
    
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    '''
    删除购物车中的商品
    '''
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
    
    
def cart_detail(request):
    '''
    展示购物车内商品
    '''
    cart = Cart(request)
    
    if not cart:
        return render(request, 'cart/empty.html')
    
    for item in cart: # 为每个物品设置表单
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'update': True}
        )
    
    coupon_apply_form = CouponApplyForm()
    
    
    # 添加推荐
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products, max_results=4)
    
    return render(request, 'cart/detail.html', {
        'cart': cart,
        'coupon_apply_form': coupon_apply_form,
        'recommended_products': recommended_products
    })

eshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  购物车
{% endblock %}

{% block content %}

<style>

  .container {
    margin-bottom: 10px !important;
  }
  
  .total {
    background-color: cornsilk;
  }

  main {
    background-image: url('{% static 'img/bg.png' %}');
  }
  
</style>

<div class="container">
  <h3>购物车</h3>
  <table class="striped highlight centered">
    <thead>
      <tr>
        <th>图片</th>
        <th>商品</th>
        <th>数量</th>
        <th>删除</th>
        <th>单价</th>
        <th>小计</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td class="img-td">
              <a href="{{ product.get_absolute_url }}">
                <img class="inline-img" src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no.PNG' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <button class="btn btn-small" type="submit"><i class="material-icons">edit</i></button>
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}"><i class="material-icons" style="color:red;">delete_forever</i></a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>合计</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price | floatformat:"2" }}</td>
        </tr>
        <tr>
          <td>
            "{{ cart.coupon.code }}" 优惠码
            ({{ cart.coupon.discount }}% off)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:"2" }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>总计</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:"2" }}
        </td>
      </tr>
      
    </tbody>
  </table>
  
  {% if recommended_products %}
  <div class="recommendations cart">
    <div class="row">
    <h5>购买该商品的用户同时购买:</h5>
    {% for p in recommended_products %}
    <div class="col s12 m2">
      <div class="card">
        <div class="card-image">
          <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}
            {% static 'img/no.PNG' %}{% endif %}">
          </a>
        </div>
        <div class="card-content truncate">
          <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
  </div>
  {% endif %}
  
  <br/>
  <p style="margin-bottom:0;display:inline-block">使用优惠码:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <button class="btn" tyle="submit">提交</button>
    {% csrf_token %}
  </form>
  <br/>
  <a href="{% url 'shop:product_list' %}" class="btn waves-effect waves-light blue lighten-3">继续购物</a>
  <a href="{% url 'orders:order_create' %}" class="btn waves-effect waves-light blue lighten-2" name="action">结算</a>
</div>

<script>
</script>

{% endblock %}

eshop/cart/templates/cart/empty.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  购物车
{% endblock %}

{% block content %}
<style>
    main {
        background-image:url({% static 'img/bg.png' %});
    }
</style>
<div class="center-align" style="">
    <h1>空空如也</h1>

    <a class="btn" href="/">去购买</a>
</div>

{% endblock %}