eshop/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

eshop/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf,
        name='admin_order_pdf'
    ),
]

eshop/orders/models.py
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from coupons.models import Coupon
from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True) # braintree返回的事务id
    
    coupon = models.ForeignKey(Coupon, related_name='orders',
                                null=True, on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0, validators=[
                            MinValueValidator(0), MinValueValidator(100)])
    
    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal('100'))
    

class OrderItem(models.Model):
    '''
    中间表
    '''
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE
    )
    
    product = models.ForeignKey(
        Product,
        related_name='order_items',
        on_delete=models.CASCADE
    )
    
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return '{}'.format(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

eshop/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    '''
    创建订单表单
    '''
    
    email = forms.TextInput(attrs={'class': 'validate'})
    first_name = forms.TextInput(attrs={'class': 'validate'})
    last_name = forms.TextInput(attrs={'class': 'validate'})
    address = forms.TextInput(attrs={'class': 'validate'})
    postal_code = forms.TextInput(attrs={'class': 'validate'})
    city = forms.TextInput(attrs={'class': 'validate'})
    
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

eshop/orders/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
import weasyprint

from cart.cart import Cart
from .models import OrderItem, Order
from .forms import OrderCreateForm
from .tasks import order_created


def order_create(request):
    '''
    创建订单
    '''
    # 从会话中获取购物车信息
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False) # commit=False不存入数据库
            
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            
            # 清空购物车
            cart.clear()
            # 调用异步任务
            order_created.delay(order.id) # delay方法异步执行
            
            # 将定单id保存到会话中，用于之后的payment应用
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
            # return render(request, 'orders/order/created.html', {'order': order})
    
    else:
        form = OrderCreateForm()

    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})


@staff_member_required
def admin_order_detail(request, order_id):
    '''
    自定义admin面板视图
    '''
    order = get_object_or_404(Order, id=order_id)
    return render(
        request,
        'admin/orders/order/detail.html', #在当前应用的templates目录下，按该解构创建模板
        {
            'order': order,
        }
    )


@staff_member_required
def admin_order_pdf(request, order_id):
    '''
    在admin面板中添加导出pdf操作
    '''
    order = get_object_or_404(Order, id=order_id)
    # 将渲染过后的模板转化为字符串
    html = render_to_string('orders/order/pdf.html', {'order': order})
    
    resp = HttpResponse(content_type='application/pdf')
    resp['Content-Disposition'] = 'filename="order_{}.pdf"'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(
        resp,
        # stylesheets=[weasyprint.CSS(
        # settings.STATIC_ROOT + 'css/pdf.css')]
        stylesheets=[weasyprint.CSS('https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css')],
    )
    
    return resp

eshop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    订单信息
{% endblock %}

{% block content %}

<style>

    .offset-m3 {
        padding-top: 15px !important;
    }

    h2 {
        border-left: 6px solid #f33c3ca1;
    }
    
    main {
        background-image: url('{% static 'img/bg.png' %}');
    }
</style>

<div class="container">
    <h2>订单信息</h2>
</div>

<div class="container center-align">
    
    <div>
        <h4>你的订单</h4>
        
        <ul>
            {% for item in cart %}
            <li>
                {{ item.quantity }} * {{ item.product.name }}
                <span>${{ item.total_price|floatformat:"2" }}</span>
            </li>
            {% endfor %}
            {% if cart.coupon %}
            <li>
                "{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% off)
                <span> -${{ cart.get_discount|floatformat:"2" }}</span>
            </li>
            {% endif %}
        </ul>
        <p>总计: ${{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
    </div>
    
    <div class="container" style="background:white">
        <div class="row">
            <div class="col m6 offset-m3 s12">
                    <form class="col s12" method="POST" action=".">
                      <div class="row">
                        <div class="input-field col s12">
                          {{ form.email }}
                          <label for="id_email">电子邮箱</label>
                        </div>
                        <div class="input-field col s12">
                          {{ form.first_name }}
                          <label for="id_first_name">名</label>
                        </div>
                        <div class="input-field col s12">
                          {{ form.last_name }}
                          <label for="id_last_name">姓</label>
                        </div>
                        <div class="input-field col s12">
                          {{ form.city }}
                          <label for="id_city">城市</label>
                        </div>
                        <div class="input-field col s12">
                          {{ form.address }}
                          <label for="id_address">地址</label>
                        </div>
                        <div class="input-field col s12">
                          {{ form.postal_code }}
                          <label for="id_postal_code">邮编</label>
                        </div>
                        <div class="input-field col s12">
                            {% csrf_token %}
                            <button class="btn" type="submit">去付款</button>
                        </div>
                      </div>
                    </form>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

eshop/orders/templates/orders/order/pdf.html
<html> 
<body> 
  <h2>My Shop</h2> 
  <p> 
    发票号： {{ order.id }}</br> 
    <span class="secondary"> 
      {{ order.created|date:"M d, Y" }} 
    </span> 
  </p> 
 
  <h3>账单信息</h3> 
  <p> 
    {{ order.first_name }} {{ order.last_name }}<br> 
    {{ order.email }}<br> 
    {{ order.address }}<br> 
    {{ order.postal_code }}, {{ order.city }} 
  </p> 
 
  <h3>商品信息</h3> 
  <table> 
    <thead> 
      <tr> 
        <th>商品</th> 
        <th>单价</th> 
        <th>数量</th> 
        <th>小计</th> 
      </tr> 
    </thead> 
    <tbody> 
      {% for item in order.items.all %} 
        <tr class="row{% cycle "1" "2" %}"> 
          <td>{{ item.product.name }}</td> 
          <td class="num">${{ item.price }}</td> 
          <td class="num">{{ item.quantity }}</td> 
          <td class="num">${{ item.get_cost }}</td> 
        </tr> 
      {% endfor %} 
      <tr class="total"> 
        <td colspan="3">总计</td> 
        <td class="num">${{ order.get_total_cost }}</td> 
      </tr> 
    </tbody> 
  </table> 
     
  <span class="btn {% if order.paid %}green{% else %}red{% endif %} right"> 
    {% if order.paid %}已付{% else %}未付款{% endif %} 
  </span> 
</body> 
</html>